### ISSUE TITLE
ypkg build support with chroot

### ISSUE THREAD

**Issue by aydemir** [solus-project/ypkg#13]
https://plus.google.com/103422631851829632052/posts/a8FLgPdeemm

**Comment by ikeydoherty** [comment]
I'm not sure why you're showing me this? Solus has `evobuild` for chroot building,  which is the recommended method for building packages. We've had it a long time too.

Are you attempting to port `ypkg` to Pisi Linux?

**Comment by ikeydoherty** [comment]
OK closing completely useless issue due to being some weird Pisilinux/Anka stuff and no response..
