### ISSUE TITLE
Add python actionable macros

### ISSUE THREAD

**Issue by JoshStrobl** [solus-project/ypkg#16]
Proposal / feature request to add the following Python macros:

Macro | Action
---- | ----
`python_setup` | `python setup.py build`
`python_install` | `python setup.py install --root=%installroot% --no-compile -O0`
`python3_setup` | `python3 setup.py build`
`python3_install` | `python3 setup.py install --root=%installroot% --no-compile -O0`

**Comment by ikeydoherty** [comment]
Why no compile? We want to ship the pyc
