### ISSUE TITLE
[Feature] Default FileType for /usr/share/help

### ISSUE THREAD

**Issue by DataDrake** [solus-project/ypkg#18]
Currently, metadata.py will mark any file in /usr/share/help as data and individually list them in the PSPEC file. I suggest that we set a default FileType for /usr/share/help to prevent this verbose behavior.

Perhaps "doc"? It used to just be "data"

Example:

`
<Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="data">/usr/share/help/C/zenity/calendar.page</Path>
            <Path fileType="data">/usr/share/help/C/zenity/color-selection.page</Path>
            <Path fileType="data">/usr/share/help/C/zenity/entry.page</Path>
            <Path fileType="data">/usr/share/help/C/zenity/error.page</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-calendar-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-colorselection-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-entry-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-error-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-fileselection-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-forms-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-information-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-list-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-notification-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-password-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-progress-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-question-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-scale-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-text-screenshot.png</Path>
            <Path fileType="data">/usr/share/help/C/zenity/figures/zenity-warning-screenshot.png</Path>
           <Path fileType="data">/usr/share/help/C/zenity/file-selection.page</Path> ............
</Files>
`

vs

`<Path fileType="data">/usr/share/help</Path>`

**Comment by ikeydoherty** [comment]
Fixed ty :)

**Comment by DataDrake** [comment]
thanks ikey!
