### ISSUE TITLE
[Feature Request] Support for GitHub as a source format

### ISSUE THREAD

**Issue by DataDrake** [solus-project/ypkg#19]
It would be super nice if I could pull source from github for some things, say PCSX2 for example.

The idea would be that instead of tar + sha256, it would do a local clone, checkout a specific Tag, and then proceed building as normal.

If security is a concern, ignore me.

**Comment by ikeydoherty** [comment]
The only downside I can see would be what is an acceptable clone depth?

**Comment by DataDrake** [comment]
Most of the time all I need is a specific tag. Nothing else in the history or other branches is needed.

**Comment by ikeydoherty** [comment]
Initial support in 3e11213da47515286aea45ff88982d11c492ae28 - going to need a fair bit of testing first

**Comment by ikeydoherty** [comment]
Kinda solved. >_>
