### ISSUE TITLE
Unbreak Haskell

### ISSUE THREAD

**Issue by ikeydoherty** [solus-project/ypkg#29]
The latest ypkg change for `.a` files went that bit too far:
4ac22fb500c3c6c594d6a39aac65c3132d3f8a02

Effectively we're removing the symbol tables too. strip is using default behaviour and actually doing a *full* strip on the archives, making them useless. Need to revert this change.

**Comment by ikeydoherty** [comment]
cc: @DataDrake

**Comment by DataDrake** [comment]
It's worth mentioning that `--strip-debug` does not affect the symbol tables enough to brick static linking. It only happens when you remove `.comment` or `.note`

**Comment by ikeydoherty** [comment]
That's actually not the problem here. When you call `strip -R .comment` it actually does it's normal behaviour as if it had been invoked as `strip`. I'm guessing its a binutils bug but meh.
