### ISSUE TITLE
merge source cache

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/ypkg#3]
Have one source cache for yauto, yconvert, ypkg, evobuild.

So if you use yauto or yconvert to start/convert a package it downloads the source to /var/cache/eopkg/source

and then ypkg AND evobuild use that cache of src files to build.

Saves 3 downloads for one file, especially when source files can get quite large.

**Comment by ikeydoherty** [comment]
That would require them all to have root privileges - not exactly acceptable. Perhaps an option to disable unlink of files ?
